/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package builderdesignpattern;

import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.xml.sax.Attributes;


/**
 *
 * @author 123456789
 */
public class Portal_form extends javax.swing.JFrame {

    /**
     * Creates new form PortalForm
     */  
   
     
    
         String FristName ;
         String LastName ;
         String EmailAddress ;
         String webiste ;
         int phone;
         int  LicenseCountry;
         int LicenseNumber ;
         int PracticeYear;  
         String gender;          
         String degree; 
         String major ; 
         String school ; 
         int  year ; 
         String Coutry; 
         String City ; 
         String State; 
         String Postcode  ; 
         Vector<Address> MorAdd = new Vector<Address>();
         Vector<Education> MorEdu = new Vector<Education>();

          
         String   specializationArea; 
         int   startYear ; 
        
         
         
    public Portal_form() {
        initComponents();
        
       
        
    }  

    public Portal_form(String FristName, String LastName, String EmailAddress, String webiste, int phone, int LicenseCountry, int LicenseNumber, int PracticeYear, String gender, String degree, String major, String school, int year, String Coutry, String City, String Postcode,  String specializationArea, int startYear) {
        this.FristName = FristName;
        this.LastName = LastName;
        this.EmailAddress = EmailAddress;
        this.webiste = webiste;
        this.phone = phone;
        this.LicenseCountry = LicenseCountry;
        this.LicenseNumber = LicenseNumber;
        this.PracticeYear = PracticeYear;
        this.gender = gender;
        this.degree = degree;
        this.major = major;
        this.school = school;
        this.year = year;
        this.Coutry = Coutry;
        this.City = City;
        this.Postcode = Postcode;
             this.specializationArea = specializationArea;
        this.startYear = startYear;
    }
      
    
    // insert newdentist information 
     public void InsertNewpersonalInf()
     { 
          FristName = firstnametext.getText() ; 
          LastName = lastnametext.getText();
          EmailAddress =EmailAddresstext.getText(); 
          webiste = websitetext.getText(); 
           phone = Integer.parseInt(phonetext.getText());
         
     }  
     // insert Biography information 
     public void InsertBiography()
     {
           LicenseCountry = Integer.parseInt(licensecountrytext.getText());  
          LicenseNumber =  Integer.parseInt(licensenumbertext.getText())  ; 
          PracticeYear=  Integer.parseInt(practiceyeartext.getText()) ; 
          gender = gendertext.getText(); 
         
         
     } 
     public void InsertEducation()
     { 
          degree = degreestext.getText(); 
          major = majortext.getText(); 
          school= schooltext.getText() ; 
          year = Integer.parseInt(yeartext.getText()); 
        Education edu = new Education(degree, major, school, year);
        MorEdu.add(edu);
     } 
     public void InsertAddress() 
     {
          Coutry = countrytext.getText(); 
          City = citytext.getText(); 
          State = statetext.getText(); 
          Postcode = postcodetext.getText() ; 
          Address Add = new Address(Coutry, State, City, Postcode);
          MorAdd.add(Add);
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstnametext = new javax.swing.JTextField();
        EmailAddresstext = new javax.swing.JTextField();
        websitetext = new javax.swing.JTextField();
        lastnametext = new javax.swing.JTextField();
        phonetext = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        licensecountrytext = new javax.swing.JTextField();
        licensenumbertext = new javax.swing.JTextField();
        practiceyeartext = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gendertext = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        degreestext = new javax.swing.JTextField();
        majortext = new javax.swing.JTextField();
        schooltext = new javax.swing.JTextField();
        yeartext = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        countrytext = new javax.swing.JTextField();
        citytext = new javax.swing.JTextField();
        statetext = new javax.swing.JTextField();
        postcodetext = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        SpecailistCheckbox = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("New Dentist"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel4.setText("Website");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 93, 66, -1));

        jLabel5.setText("Email Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 62, -1, -1));

        jLabel6.setText("Phone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 50, -1));
        jPanel1.add(firstnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 129, -1));
        jPanel1.add(EmailAddresstext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 130, -1));
        jPanel1.add(websitetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 360, -1));
        jPanel1.add(lastnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 127, -1));
        jPanel1.add(phonetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 127, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Biography"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("License Country");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        jLabel7.setText("License Number ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel8.setText("Years In Practice ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel2.add(licensecountrytext, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 27, 240, -1));
        jPanel2.add(licensenumbertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 110, -1));
        jPanel2.add(practiceyeartext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 112, -1));

        jLabel9.setText("Gender");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));
        jPanel2.add(gendertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 50, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 470, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Education"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 41, -1, -1));

        jLabel11.setText("Degrees");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel12.setText("Major ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel13.setText("School ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel14.setText("Year");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 32, -1));
        jPanel3.add(degreestext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 135, -1));
        jPanel3.add(majortext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 280, -1));

        schooltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schooltextActionPerformed(evt);
            }
        });
        jPanel3.add(schooltext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 280, -1));
        jPanel3.add(yeartext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 50, -1));

        jButton1.setText("Add More");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 280, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 470, 170));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("County");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel16.setText("City");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel17.setText("State");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel18.setText("Post Code");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jButton2.setText("Add More");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 150, 120));
        jPanel4.add(countrytext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, -1));
        jPanel4.add(citytext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 160, -1));
        jPanel4.add(statetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 160, -1));
        jPanel4.add(postcodetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 480, 170));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Speciality"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SpecailistCheckbox.setText("is Specialist");
        SpecailistCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecailistCheckboxActionPerformed(evt);
            }
        });
        jPanel5.add(SpecailistCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 290, 60));

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, 150, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schooltextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schooltextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schooltextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:  
        InsertNewpersonalInf();
        InsertBiography();
        InsertEducation();
        InsertAddress() ;      
        
        
        
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
               degree = degreestext.getText(); 
          major = majortext.getText(); 
          school= schooltext.getText() ; 
          year = Integer.parseInt(yeartext.getText()); 
          Education  edumor = new Education(degree, major, school, year);
          MorEdu.add(edumor);
             

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
             Coutry = countrytext.getText(); 
          City = citytext.getText(); 
          State = statetext.getText(); 
          Postcode = postcodetext.getText() ; 
          Address Add = new Address(Coutry, State, City, Postcode);
          MorAdd.add(Add);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SpecailistCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecailistCheckboxActionPerformed
 
           
    }//GEN-LAST:event_SpecailistCheckboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portal_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portal_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portal_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portal_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portal_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailAddresstext;
    private javax.swing.JCheckBox SpecailistCheckbox;
    private javax.swing.JTextField citytext;
    private javax.swing.JTextField countrytext;
    private javax.swing.JTextField degreestext;
    private javax.swing.JTextField firstnametext;
    private javax.swing.JTextField gendertext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField lastnametext;
    private javax.swing.JTextField licensecountrytext;
    private javax.swing.JTextField licensenumbertext;
    private javax.swing.JTextField majortext;
    private javax.swing.JTextField phonetext;
    private javax.swing.JTextField postcodetext;
    private javax.swing.JTextField practiceyeartext;
    private javax.swing.JTextField schooltext;
    private javax.swing.JTextField statetext;
    private javax.swing.JTextField websitetext;
    private javax.swing.JTextField yeartext;
    // End of variables declaration//GEN-END:variables
}
